### ISSUE TITLE
supporting dark mode

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#142]
you can switch some color when your browser is dark mode.

you have to switch background, text and border colors at least.

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: #fff;
  }
}
```
