### ISSUE TITLE
hp address in a mail

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#47]
when a game is generated, mails are sent to both players.
but in the message, server address is "localhost".
so you have to make it easier to adjust actual server address.

**Comment by o-jill** [comment]
made configurable in 43538fd.
plz edit config/settings.yaml.
dont forget to put '/' at the end

```yaml
# global settings
support_url:  "http://sup.port.com/"
domain:       "your.example.com"
base_url:     "http://your.example.com/~user/cgi-bin/washcrus/"
#              http://your.example.com/~user/cgi-bin/washcrus/washcrus.rb
#              will be the top page.
```
