### ISSUE TITLE
Settings which administrator users can change on the web.

### ISSUE THREAD

**Issue by o-jill** [o-jill/washcrus#92]
some settings should be allowed to change on your browsers.

here, you will pick them up and make them configurable.
ex. title, base url, signature and so on.

this issue is one of #74.

**Comment by o-jill** [comment]
```yaml
# config/settings.yaml

# global settings
support_url:    "http://www.example.com/washcrussupport/bbs"
domain:         "www.example.com"
base_url:       "http://www.example.com/cgi-bin/washcrus/"
```
support_url is used in a menu.
domain is not used yet.
base_url is used in a mail.
